# Generated by Django 2.1.7 on 2019-02-22 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('location', models.CharField(choices=[('out', 'exterior'), ('in', 'interior')], max_length=3)),
                ('cant', models.FloatField(blank=True)),
                ('description', models.TextField(null=True)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
