# Generated by Django 2.1.7 on 2019-02-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_auto_20190222_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='location',
            field=models.CharField(choices=[('out', 'exterior'), ('in', 'interior')], default='out', max_length=3),
        ),
    ]
