# Generated by Django 2.1.7 on 2019-02-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0003_auto_20190225_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='location',
            field=models.CharField(choices=[('out', 'exterior'), ('in', 'interior')], default='in', max_length=3),
        ),
    ]
