# Generated by Django 2.1.7 on 2019-03-09 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0004_auto_20190225_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='location',
            field=models.CharField(choices=[('off', 'exterior'), ('on', 'interior')], default='on', max_length=3),
        ),
    ]
