# Generated by Django 2.1.7 on 2019-03-09 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0005_auto_20190308_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='cant',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='location',
            field=models.CharField(choices=[('out', 'exterior'), ('in', 'interior')], default='in', max_length=3),
        ),
    ]
